# Generated by Django 4.2 on 2023-04-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='addres',
            new_name='address',
        ),
    ]
