# Generated by Django 4.2 on 2023-04-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_rename_addres_collaborator_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
