# Generated by Django 3.2.12 on 2023-04-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_alter_collaborator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
